### PR TITLE
Crud items

### PR DESCRIPTION
**Pull request by atbang**
Completes checkpoint 7, 8, 9, and Extra Credit (Auto Rake task).

Rspec 90.0% covered.

### CODE REVIEW

**Comment by Brit200313** [comment]
Well done!

popkey

**Comment by atbang** [comment]
Hi Brittany,

Just pulled the master down. 

One small hiccup. This has happened before and I thought we fixed it, but I can’t push to Heroku. Not sure why but Heroku will not accept my push. 

Maybe we can look at it tomorrow? 

Thanks.

Alex

**Comment by atbang** [comment]
Hi Brittany,

Just pulled the master down. 

One small hiccup. This has happened before and I thought we fixed it, but I can’t push to Heroku. Not sure why but Heroku will not accept my push. 

Maybe we can look at it tomorrow? 

Thanks.

Alex

**Comment by Brit200313** [comment]
Hi Alex,

Absolutely. Put it on the list!

Britt

On Wed, Feb 3, 2016 at 7:50 PM, Alex Bang <notifications@github.com> wrote:

> Hi Brittany,
>
> Just pulled the master down.
>
> One small hiccup. This has happened before and I thought we fixed it, but
> I can’t push to Heroku. Not sure why but Heroku will not accept my push.
>
> Maybe we can look at it tomorrow?
>
> Thanks.
>
> Alex
>
>
>
> > On Feb 3, 2016, at 7:27 PM, Brittany Martin <notifications@github.com>
> wrote:
> >
> > Well done!
> >
> > <
> https://camo.githubusercontent.com/4ad98bf74a243e508356da116c61d09017808143/68747470733a2f2f6d2e706f706b65792e636f2f6662343736332f71345a4b2e676966
> >
> > —
> > Reply to this email directly or view it on GitHub <
> https://github.com/atbang/taskminder/pull/3#issuecomment-179550636>.
> >
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/atbang/taskminder/pull/3#issuecomment-179556011>.
>



-- 
Brittany Martin
about.me/brittany.martin
sfviapgh.com

**Comment by atbang** [comment]
Hi Brittany,

I'm having network problems. I'm trying to reboot.

**Comment by Brit200313** [comment]
Oh! No worries, I'm on standby then.


On Thu, Feb 4, 2016 at 8:00 PM, Alex Bang <notifications@github.com> wrote:

> Hi Brittany,
>
> I'm having network problems. I'm trying to reboot.
>
> > On Feb 3, 2016, at 7:59 PM, Brittany Martin <notifications@github.com>
> wrote:
> >
> > Hi Alex,
> >
> > Absolutely. Put it on the list!
> >
> > Britt
> >
> > On Wed, Feb 3, 2016 at 7:50 PM, Alex Bang <notifications@github.com>
> wrote:
> >
> > > Hi Brittany,
> > >
> > > Just pulled the master down.
> > >
> > > One small hiccup. This has happened before and I thought we fixed it,
> but
> > > I can’t push to Heroku. Not sure why but Heroku will not accept my
> push.
> > >
> > > Maybe we can look at it tomorrow?
> > >
> > > Thanks.
> > >
> > > Alex
> > >
> > >
> > >
> > > > On Feb 3, 2016, at 7:27 PM, Brittany Martin <
> notifications@github.com>
> > > wrote:
> > > >
> > > > Well done!
> > > >
> > > > <
> > >
> https://camo.githubusercontent.com/4ad98bf74a243e508356da116c61d09017808143/68747470733a2f2f6d2e706f706b65792e636f2f6662343736332f71345a4b2e676966
> > > >
> > > > —
> > > > Reply to this email directly or view it on GitHub <
> > > https://github.com/atbang/taskminder/pull/3#issuecomment-179550636>.
> > > >
> > >
> > > —
> > > Reply to this email directly or view it on GitHub
> > > <https://github.com/atbang/taskminder/pull/3#issuecomment-179556011>.
> > >
> >
> >
> >
> > --
> > Brittany Martin
> > about.me/brittany.martin
> > sfviapgh.com
> > —
> > Reply to this email directly or view it on GitHub.
> >
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/atbang/taskminder/pull/3#issuecomment-180131903>.
>



-- 
Brittany Martin
about.me/brittany.martin
sfviapgh.com

**Pull request merged**
